<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTableCategories extends Migration
{

    /**
     * Migration table
     * 
     * @var string
     */
    protected $table = 'categories';


    /**
     * Run the migrations.
     *
     * There are 2 types of category records, 
     * Organic Category & Manual Category
     * 
     * Organic Category - 
     * generated by the Categories Scan process, they belongs to Channel & StorageCategories.
     * 
     * Manual Category - 
     * generated by manual insertion and has no owners.
     * 
     * @return void
     */
    public function up()
    {
        if (!Schema::hasTable($this->table)) 
        {
            Schema::create($this->table, function (Blueprint $table) 
            {
                $table->increments('id');

                // if it is Manual Category, the channel_id & storage_category_id can be null
                $table->unsignedInteger('channel_id')->nullable()->comment('reference to the channel that Organic Categories resourced from - channels.id');
                $table->unsignedInteger('storage_category_id')->nullable()->comment('reference to the storage record Organic Categories resourced from - storage_categories.id');
                
                $table->string('title')->nullable();
                $table->string('path')->nullable();
                $table->string('description')->nullable();
                $table->timestamps();
            });
        }
    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists($this->table);
    }
    
}
